// English catalogue names -> Japanese display names.
// Falls back to the raw name when unmapped so new cities never break the UI.

const PLACE_JA: Record<string, string> = {
  Tokyo: "東京",
  Kyoto: "京都",
  Osaka: "大阪",
  Nara: "奈良",
  Hokkaido: "北海道",
  Okinawa: "沖縄",
  Hiroshima: "広島",
  Kanazawa: "金沢",
  Fukuoka: "福岡",
  Seoul: "ソウル",
  Busan: "釜山",
  Taipei: "台北",
  Beijing: "北京",
  Shanghai: "上海",
  "Hong Kong": "香港",
  Bangkok: "バンコク",
  "Chiang Mai": "チェンマイ",
  Phuket: "プーケット",
  Bali: "バリ",
  Yogyakarta: "ジョグジャカルタ",
  "Kuala Lumpur": "クアラルンプール",
  Singapore: "シンガポール",
  Hanoi: "ハノイ",
  "Ho Chi Minh City": "ホーチミン",
  Manila: "マニラ",
  Cebu: "セブ",
  London: "ロンドン",
  Paris: "パリ",
  Rome: "ローマ",
  Florence: "フィレンツェ",
  Venice: "ベネチア",
  Milan: "ミラノ",
  Barcelona: "バルセロナ",
  Madrid: "マドリード",
  Lisbon: "リスボン",
  Berlin: "ベルリン",
  Munich: "ミュンヘン",
  Amsterdam: "アムステルダム",
  Vienna: "ウィーン",
  Prague: "プラハ",
  Budapest: "ブダペスト",
  Athens: "アテネ",
  Santorini: "サントリーニ",
  Stockholm: "ストックホルム",
  Copenhagen: "コペンハーゲン",
  Dublin: "ダブリン",
  Edinburgh: "エディンバラ",
  "New York City": "ニューヨーク",
  "San Francisco": "サンフランシスコ",
  "Los Angeles": "ロサンゼルス",
  "Las Vegas": "ラスベガス",
  Miami: "マイアミ",
  Vancouver: "バンクーバー",
  Toronto: "トロント",
  Montreal: "モントリオール",
  "Mexico City": "メキシコシティ",
  "Cancún": "カンクン",
  Sydney: "シドニー",
  Melbourne: "メルボルン",
  Brisbane: "ブリスベン",
  Perth: "パース",
  Auckland: "オークランド",
  Queenstown: "クイーンズタウン",
};

export function displayName(name: string | null | undefined): string {
  if (!name) return "";
  return PLACE_JA[name] ?? name;
}
